version: "3.8"

services:
  authup:
    image: tada5hi/authup-server:latest
    volumes:
      - ./service_data/auth:/usr/src/app/writable
    ports:
      - '3010:3010'
    environment:
      PORT: 3010
      ADMIN_USER: admin
      ADMIN_PASSWORD: start123
      NODE_ENV: test
      PUBLIC_URL: http://auth:3010/
      ROBOT_SECRET: zms45eboy7to1vxzkpbegqmhkchye50y1dlzrlyzc73odupsmoxdwxaozdriiv0x
    command:
      - start