version: "3.8"
volumes:
  authup_data:
services:
  authup:
    image: ghcr.io/authup/authup:latest
    ports:
      - "3000:3000"
#    environment:
#      DB_TYPE: postgres
#      DB_HOST: postgres
#      DB_USERNAME: authup
#      DB_PASSWORD: authup
#      DB_DATABASE: authup
    pull_policy: always
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    volumes:
      - authup_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: authup
      POSTGRES_USER: authup
      POSTGRES_DB: authup
    pull_policy: always