version: "3.8"

services:
  authup:
    image: ghcr.io/authup/authup:latest
    ports:
      - "3000:3000"
      - "3001:3001"
    volumes:
      - ./authup_data:/usr/src/app/writable
    command: cli start