name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: # This configuration does not affect the page_build event above
      - created


jobs:
  test:
    env:
      AUTHUP_URL: http://127.0.0.1:3010
      AUTHUP_USERNAME: ${{ secrets.ADMIN_USER }}
      AUTHUP_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      AUTHUP_ROBOT_SECRET: ${{ secrets.ROBOT_SECRET }}
    runs-on: ubuntu-latest
    services:
      authup:
        image: "tada5hi/authup-server:latest"
        env:
          PORT: 3010
          ADMIN_USER: ${{ secrets.ADMIN_USER }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ROBOT_SECRET: ${{ secrets.ROBOT_SECRET }}
          NODE_ENV: test
          PUBLIC_URL: http://authup:3010/
        ports:
          - "3010:3010"

    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: poetry
      - name: Install dependencies
        run: poetry install --no-interaction --no-root --with=dev --all-extras

      - name: Run tests with coverage
        run: |
          poetry run coverage run -m pytest
          poetry run coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true

