name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - created


jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    services:
      authup:
        image: ghcr.io/authup/authup:latest
        env:
          DB_TYPE: postgres
          DB_HOST: postgres
          DB_PORT: 5432
          DB_USERNAME: authup
          DB_PASSWORD: authup
          DB_DATABASE: authup
          ROBOT_ENABLED: true
          ROBOT_SECRET: start123
        ports:
          - "3000:3000"

      postgres:
        # Docker Hub image
        image: postgres:14
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: authup
          POSTGRES_USER: authup
          POSTGRES_DB: authup

        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --no-interaction --no-root --with=dev --all-extras

      - name: Run tests with coverage
        env:
            AUTHUP_URL: http://authup:3000/
            AUTHUP_ROBOT_SECRET: start123
        run: |
            poetry run coverage run -m pytest
            poetry run coverage xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
            token: ${{ secrets.CODECOV_TOKEN }}
            fail_ci_if_error: true

  test-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
    services:
      authup:
        image: ghcr.io/authup/authup:latest
        env:
            PORT: 3000
            ROBOT_SECRET: start123
            NODE_ENV: test
            PUBLIC_URL: http://authup:3010/
            ROBOT_ENABLED: true
        ports:
          - "3000:3000"
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Setup python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --no-interaction --no-root --with=dev --all-extras

      - name: Test with tox
        env:
            AUTHUP_URL: http://localhost:3000
            AUTHUP_ROBOT_SECRET: start123
        run: poetry run tox
