name: Python version

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - created

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]
    env:
      AUTHUP_URL: http://127.0.0.1:3010
      AUTHUP_USERNAME: ${{ secrets.ADMIN_USER }}
      AUTHUP_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      AUTHUP_ROBOT_SECRET: ${{ secrets.ROBOT_SECRET }}
    services:
      authup:
        image: "tada5hi/authup-server:latest"
        env:
          PORT: 3010
          ADMIN_USER: ${{ secrets.ADMIN_USER }}
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          ROBOT_SECRET: ${{ secrets.ROBOT_SECRET }}
          NODE_ENV: test
          PUBLIC_URL: http://authup:3010/
          ROBOT_ENABLED: true
        ports:
          - "3010:3010"
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Setup python version ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "poetry"
      - name: Install dependencies
        run: poetry install --no-interaction --no-root --with=dev --all-extras

      - name: Test with tox
        run: poetry run tox